plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

version = "${project.mod_version}"
group = rootProject.maven_group

repositories {
	maven {
		url "https://masa.dy.fi/maven"
	}
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"carpet-trencher-addition" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${stonecutter.current.project}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${loader_version}"
	modImplementation "carpet:fabric-carpet:${carpet_core_version}"
}

processResources {
	def version = project.version
	def minecraftVer = stonecutter.current.version

	inputs.property "version", version
	inputs.property "minecraftVer", minecraftVer

	filesMatching("fabric.mod.json") {
		expand(
				version: version,
				minecraftVer: minecraftVer
		)
	}
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_${projectName}" }
	}
}

tasks.named("remapJar") {
	archiveBaseName = "carpet-trencher-addition"
	archiveVersion = "${project.version}+mc${stonecutter.current.version}"
}

tasks.named("remapSourcesJar") {
	archiveBaseName = "carpet-trencher-addition"
	archiveVersion = "${project.version}+mc${stonecutter.current.version}"
}