buildscript {
	repositories {
		maven {
			name = "Fabric"
			url = "https://maven.fabricmc.net/"
		}
		mavenCentral()
		gradlePluginPortal()
	}
	dependencies {
		classpath "net.fabricmc:fabric-loom:1.15.5"
	}
}

plugins {
	id 'maven-publish'
}

def mcVersion = stonecutter.current.version
def minecraftVer = project.findProperty("minecraft_version") ?: mcVersion
def isModern = mcVersion.startsWith('26.')

if (isModern) {
	apply plugin: 'net.fabricmc.fabric-loom'
} else {
	apply plugin: 'net.fabricmc.fabric-loom-remap'
}

version = "${project.mod_version}"
group = rootProject.maven_group

base {
	archivesName = "carpet-trencher-addition-${mcVersion}"
}

repositories {
	maven {
		url "https://masa.dy.fi/maven"
	}
	mavenCentral()
}

loom {
	splitEnvironmentSourceSets()
	mods {
		"carpet-trencher-addition" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${mcVersion}"

	if (!isModern) {
		mappings loom.officialMojangMappings()
		modImplementation "net.fabricmc:fabric-loader:${loader_version}"
		modImplementation "carpet:fabric-carpet:${carpet_core_version}"
		modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
	} else {
		implementation "net.fabricmc:fabric-loader:${loader_version}"
		implementation "carpet:fabric-carpet:${property("carpet_core_version")}"
		implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
	}
}

processResources {
	inputs.property "version", project.version
	inputs.property "minecraftVer", minecraftVer
	filesMatching("fabric.mod.json") {
		expand(
				version: project.version,
				minecraftVer: minecraftVer
		)
	}
}

def javaVersion = isModern ? 25 : 21

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.toVersion(javaVersion)
	targetCompatibility = JavaVersion.toVersion(javaVersion)
}

tasks.withType(JavaCompile).configureEach {
	options.release = javaVersion
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.name}" }
	}
}

tasks.named("jar") {
	archiveBaseName = "carpet-trencher-addition"
	archiveVersion = "${project.version}+mc${project.findProperty("game_version")}"
}

tasks.named("sourcesJar") {
	archiveBaseName = "carpet-trencher-addition"
	archiveVersion = "${project.version}+mc${project.findProperty("game_version")}"
}

if (!isModern) {
	tasks.named("remapJar") {
		archiveBaseName = "carpet-trencher-addition"
		archiveVersion = "${project.version}+mc${project.findProperty("game_version")}"
	}
	tasks.named("remapSourcesJar") {
		archiveBaseName = "carpet-trencher-addition"
		archiveVersion = "${project.version}+mc${project.findProperty("game_version")}"
	}
}